use  Hospital_Analytics;
--ORDER BY Queries
--Q1 Display all patients ordered by age ascending.
      select * from patients 
      order by age;
      
--Q2 Display all doctors ordered by experience descending.
      select * from doctors order by experience desc;

--Q3 Display all billing records ordered by total amount highest to lowest.
      select * from billing 
      order by total_amount desc;

--Q4 Display medicines ordered by stock quantity descending.
      select * from medicines 
      order by stock_quantity desc;

==Q5 Display appointments ordered by appointment date.
     select * from appointments order by appointment_date;
     
--GROUP BY Queries
--Q6 Find number of patients in each blood group.
      select blood_group,count(*) from patients 
      group by blood_group

--Q7 Find total salary department wise from staffs table.
      select department_id,sum(salary) from staffs 
      group by department_id

--Q8 Find number of doctors in each department.
     select department_id,count(*) from doctors 
     group by department_id

--Q9 Find total revenue generated by payment method.
     SELECT payment_method, SUM(amount_paid) AS total_revenue FROM payments
     GROUP BY payment_method;
  

--Q10 Find average room charge by room type.
       select  room_type,avg(room_charge) as avgcharge_perroom from rooms 
       group by room_type

--HAVING Queries
--Q11 Find departments having more than 1 doctor.
        select department_id,count(*) from doctors 
        group by department_id 
        having count(*) > 1;

--Q12 Find blood groups having more than 2 patients.
	 select blood_group, count(*) from patients 
     group by blood_group 
     having count(*) > 2;
	
--Q13 Find payment methods where total amount paid is greater than 5000.
       SELECT payment_method,SUM(amount_paid) AS total_amount FROM payments
       GROUP BY payment_method
       HAVING SUM(amount_paid) > 5000;

--Q14 Find room types having average room charge greater than 3000.
         select room_type,avg(room_charge) from rooms 
         group by room_type
         having avg(room_charge) > 3000;

--Q15 Find doctors whose average experience is greater than 8 years department wise.
       select department_id,avg(experience) from doctors
       group by department_id
       having avg(experience) > 8;

--Q16 Display patient name and doctor name for all appointments.
SELECT p.patient_name, d.doctor_name
FROM appointments AS a
JOIN patients AS p
ON a.patient_id = p.patient_id
JOIN doctors AS d
ON a.doctor_id = d.doctor_id;

--Q17 Display patient name, appointment date, and appointment status.
SELECT P.PATIENT_NAME,A.APPOINTMENT_DATE,A.STATUS
FROM APPOINTMENTS AS A
JOIN PATIENTS AS P
ON P.PATIENT_ID = A.PATIENT_ID;

--Q18 Display patient name, doctor name, and department name.
SELECT P.PATIENT_NAME,D.DOCTOR_NAME,DEPART.DEPARTMENT_NAME FROM APPOINTMENTS AS A
JOIN PATIENTS AS P ON P.PATIENT_ID = A.PATIENT_ID
JOIN DOCTORS AS D ON D.DOCTOR_ID = A.DOCTOR_ID
JOIN DEPARTMENTS AS DEPART ON D.DEPARTMENT_ID = DEPART.DEPARTMENT_ID;

--Q19 Display patient name and total bill amount.
SELECT P.PATIENT_NAME, B.TOTAL_AMOUNT FROM BILLING AS B 
JOIN PATIENTS AS P
ON P.PATIENT_ID = B.PATIENT_ID;

--Q20 Display all patients and their appointment IDs.
Include patients without appointments.
SELECT P.PATIENT_ID,P.PATIENT_NAME,A.APPOINTMENT_ID FROM PATIENTS AS P 
LEFT JOIN APPOINTMENTS AS A ON P.PATIENT_ID = A.PATIENT_ID;


--Q21 Find patients who do not have any appointments.
SELECT P.PATIENT_ID,P.PATIENT_NAME,A.APPOINTMENT_ID FROM PATIENTS  AS P 
LEFT JOIN APPOINTMENTS AS A ON P.PATIENT_ID = A.PATIENT_ID
WHERE APPOINTMENT_ID IS  NULL;

--Q22 Display all doctors and appointment IDs.
Include doctors without appointments.
SELECT D.DOCTOR_NAME,A.APPOINTMENT_ID FROM DOCTORS  AS D 
LEFT JOIN APPOINTMENTS AS A ON D.DOCTOR_ID = A.DOCTOR_ID;

--Q23 Find number of appointments handled by each doctor.
SELECT D.DOCTOR_NAME,COUNT(*) AS HANDLED_BY_DOCTOR FROM APPOINTMENTS AS A
LEFT JOIN DOCTORS AS D ON A.DOCTOR_ID = D.DOCTOR_iD
GROUP BY  D.DOCTOR_NAME;

--Q24 Display all possible doctor-room combinations.
SELECT D.DOCTOR_NAME,R.ROOM_TYPE FROM ROOMS AS R
CROSS JOIN DOCTORS AS D;

--Q25 Display patient name, doctor name, bill amount, and payment method.
SELECT P.PATIENT_NAME,D.DOCTOR_NAME,B.TOTAL_AMOUNT,PM.PAYMENT_METHOD FROM APPOINTMENTS AS A
JOIN PATIENTS AS P ON P.PATIENT_ID = A.PATIENT_ID
JOIN DOCTORS AS D ON D.DOCTOR_ID = A.DOCTOR_ID
JOIN BILLING AS B ON  P.PATIENT_ID = B.PATIENT_ID
JOIN PAYMENTS AS PM ON B.BILL_ID = PM.BILL_ID

--Q26 Display all patient names and doctor names in a single column
SELECT patient_name AS names
FROM patients
UNION
SELECT doctor_name
FROM doctors;



--Subquery
-Q27 Find patients whose age is greater than the average age of all patients.
SELECT *
FROM patients
WHERE age > (
    SELECT AVG(age)
    FROM patients
);
-Q28 Find doctor(s) having maximum experience.
select * from doctors
 where experience =(  
     select max(experience) from doctors 
     );

-Q29 Find rooms having room charge greater than average room charge.
select * from rooms 
where  room_charge > (
    select avg(room_charge) from rooms
    );
-Q30 Find patients whose patient_id exists in billing table.
SELECT *
FROM patients
WHERE patient_id IN (
    SELECT patient_id
    FROM billing
);
-Q31 Find doctors working in departments located on floor number 1.
SELECT doctor_name
FROM doctors
WHERE department_id IN (
    SELECT department_id
    FROM departments
    WHERE floor_no = 1
);
-Q32 Find medicines whose price is greater than any medicine price above 100.
SELECT *
FROM medicines
WHERE price > ANY (
    SELECT price
    FROM medicines
    WHERE price > 100
);
-Q33 Find doctors whose experience is greater than average experience of their department.
SELECT *
FROM doctors d1
WHERE experience > (
    SELECT AVG(experience)
    FROM doctors d2
    WHERE d1.department_id = d2.department_id
);
-Q34 Find patients whose bill amount is greater than average bill amount.
SELECT *
FROM billing
WHERE total_amount > (
    SELECT AVG(total_amount)
    FROM billing
);
-Q35 Find patients who have at least one appointment.
SELECT *
FROM patients p
WHERE EXISTS (
    SELECT 1
    FROM appointments a
    WHERE p.patient_id = a.patient_id
);
-Q36 Find doctors who do not have any appointments.
SELECT *
FROM doctors d
WHERE NOT EXISTS (
    SELECT 1
    FROM appointments a
    WHERE d.doctor_id = a.doctor_id
);

--CASE Statement
--- Q37 Basic CASE
Display patient name and age category:
- Child → age < 18
- Adult → age between 18 and 59
- Senior Citizen → age 60 and above

SELECT PATIENT_ID,PATIENT_NAME,AGE, 
CASE 
  WHEN AGE < 18 THEN 'CHILD'
  WHEN AGE BETWEEN 18 AND 59 THEN 'ADULT'
  WHEN AGE >= 60 THEN 'Senior_Citize'
END AS AGE_CATEGORY
 FROM PATIENTS;
   
---Q38 Display staff name, salary, and salary status:
- High Salary → salary > 50000
- Medium Salary → salary between 30000 and 50000
- Low Salary → salary < 30000
SELECT STAFF_NAME,SALARY,
CASE 
 WHEN SALARY > 50000 THEN 'HIGH SALARY'
 WHEN SALARY BETWEEN 30000 AND 50000 THEN 'MEDIUM SALARY'
 WHEN SALARY < 30000 THEN 'LOW SALARY'
END AS SALARY_STATUS
FROM STAFFS

--- Q39 Display bill id, total amount, and billing category:
- Expensive → amount > 10000
- Moderate → amount between 5000 and 10000
- Cheap → amount < 5000

SELECT BILL_ID,TOTAL_AMOUNT AS AMOUNT,
  CASE
     WHEN TOTAL_AMOUNT > 10000 THEN 'Expensive'  
     WHEN TOTAL_AMOUNT BETWEEN 5000 AND 10000 THEN 'Moderate'
     WHEN TOTAL_AMOUNT < 5000 THEN  'Cheap'
     END AS Billing_category
	FROM BILLING;
    
--Q40 Display appointment id and status message:
- Completed → "Visit Finished"
- Pending → "Waiting for Visit"
- Cancelled → "Appointment Cancelled"

SELECT APPOINTMENT_ID,
CASE
   WHEN STATUS = 'Completed' THEN 'Visit Finished'
   WHEN STATUS = 'Pending' THEN 'Waiting for Visit'
   WHEN STATUS = 'Cancelled' THEN 'Appointment Cancelled'
END AS STATUS_MESSAGE
FROM APPOINTMENTS;

--WINDOW FUNCTIONS 
--Q41 Display patient name, bill amount, and assign row numbers based on highest bill amount.
SELECT p.patient_name,b.total_amount,
       ROW_NUMBER() OVER( ORDER BY b.total_amount DESC) AS high_billing
FROM billing AS b
JOIN patients AS p
ON b.patient_id = p.patient_id;

--Q42 RANK() Display doctor name and experience rank from highest to lowest experience.
SELECT DOCTOR_NAME,EXPERIENCE,
RANK() OVER(ORDER BY EXPERIENCE DESC) AS HIGH_LOW_EXPERIENCE
FROM DOCTORS;
--Q43 Display medicines ranked by price using dense rank.
SELECT *,
DENSE_RANK() OVER(ORDER BY PRICE DESC) AS PRICE_RANK
FROM MEDICINES;
--Q44  Display doctors with row numbers department wise.
SELECT DOCTOR_NAME,EXPERIENCE,
ROW_NUMBER() OVER(PARTITION BY DEPARTMENT_ID ORDER BY EXPERIENCE) AS DEPARTMENT_WISE_RANK
FROM DOCTORS;

--Q45  Display staff salary rank within each department.
SELECT STAFF_NAME,SALARY,DEPARTMENT_ID,
RANK() OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) AS SALARY_RANK
FROM STAFFS;

--Q46 LEAD() Display patient bills along with next bill amount.
SELECT P.PATIENT_NAME,B.TOTAL_AMOUNT,
LEAD(TOTAL_AMOUNT) OVER ( PARTITION BY B.PATIENT_ID ORDER BY B.BILL_DATE) AS NEXT_BILLAMOUNT
FROM BILLING AS B
JOIN PATIENTS AS P
ON P.PATIENT_ID = B.PATIENT_ID;

--Q47 LAG() Display patient bills along with previous bill amount.
SELECT P.PATIENT_NAME,B.TOTAL_AMOUNT,
LAG(TOTAL_AMOUNT) OVER ( PARTITION BY B.PATIENT_ID ORDER BY B.BILL_DATE) AS PREVIOUS_BILLAMOUNT
FROM BILLING AS B
JOIN PATIENTS AS P
ON P.PATIENT_ID = B.PATIENT_ID;

--Q48  Display highest salary in each department for every staff member.
SELECT STAFF_NAME,DEPARTMENT_ID,SALARY,
FIRST_VALUE(SALARY) OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) AS HIGH_SALARY
FROM STAFFS;
 
--Q49 Display running total of billing amounts ordered by bill date.
SELECT PATIENT_ID,TOTAL_AMOUNT,BILL_DATE,
SUM(TOTAL_AMOUNT) OVER (ORDER BY BILL_DATE) AS ORDER_BY_DATE
FROM BILLING;

--Q50  Display average room charge for every room type without grouping rows.
SELECT room_id,
       room_type,
       room_charge,
       AVG(room_charge) OVER(
           PARTITION BY room_type
       ) AS avg_room_charge
FROM rooms;

--Q51 Find top 5 patients with highest billing amount.
SELECT P.PATIENT_ID,P.PATIENT_NAME,SUM(TOTAL_AMOUNT) AS TOTAL_BILL
FROM BILLING AS B
JOIN PATIENTS AS P ON P.PATIENT_ID = B.PATIENT_ID
GROUP BY P.PATIENT_ID,P.PATIENT_NAME
ORDER BY TOTAL_BILL DESC
LIMIT 5;
--Q52 Find department wise total number of doctors.
SELECT DP.DEPARTMENT_NAME,
       COUNT(D.DOCTOR_ID) AS TOTAL_DOCTORS
FROM DEPARTMENTS AS DP
JOIN DOCTORS AS D
ON D.DEPARTMENT_ID = DP.DEPARTMENT_ID
GROUP BY DP.DEPARTMENT_NAME;

--Q53 Find monthly total revenue from billing table.
SELECT MONTH(BILL_DATE) AS MONTH_NO,
       SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BILLING
GROUP BY MONTH(BILL_DATE)
ORDER BY MONTH_NO;
--Q54 Find doctor handling highest number of appointments.
SELECT D.DOCTOR_NAME,
       COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
FROM APPOINTMENTS AS A
JOIN DOCTORS AS D
ON D.DOCTOR_ID = A.DOCTOR_ID

GROUP BY D.DOCTOR_NAME

ORDER BY TOTAL_APPOINTMENTS DESC

LIMIT 1;
--Q55 Find most used payment method.
SELECT PAYMENT_METHOD,
       COUNT(*) AS TOTAL_USAGE
FROM PAYMENTS

GROUP BY PAYMENT_METHOD

ORDER BY TOTAL_USAGE DESC

LIMIT 1;
--Q56 Find average room charge room-type wise.
SELECT ROOM_TYPE,
       AVG(ROOM_CHARGE) AS AVG_ROOM_CHARGE
FROM ROOMS

GROUP BY ROOM_TYPE;
--Q57 Find top 3 expensive medicines.
SELECT *
FROM MEDICINES

ORDER BY PRICE DESC

LIMIT 3;
--Q58 Find patients having more than 2 appointments.
SELECT P.PATIENT_ID,
       P.PATIENT_NAME,
       COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
FROM APPOINTMENTS AS A
JOIN PATIENTS AS P
ON P.PATIENT_ID = A.PATIENT_ID

GROUP BY P.PATIENT_ID, P.PATIENT_NAME

HAVING COUNT(A.APPOINTMENT_ID) > 2;
--Q59 Find department wise average doctor experience.
SELECT DP.DEPARTMENT_NAME,
       AVG(D.EXPERIENCE) AS AVG_EXPERIENCE
FROM DOCTORS AS D
JOIN DEPARTMENTS AS DP
ON DP.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY DP.DEPARTMENT_NAME;

--Q60 Find medicines with low stock quantity (less than 20).
SELECT * FROM MEDICINES
WHERE STOCK_QUANTITY < 20;

