create DATABASE hospital_analytics;
use Hospital_Analytics;

CREATE TABLE PATIENTS(
    PATIENT_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PATIENT_NAME VARCHAR(40) NOT NULL,
    GENDER VARCHAR(25) NOT NULL,
    AGE INT NOT NULL,
    PHONE BIGINT NOT NULL,
    BLOOD_GROUP VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL
    );
    
    CREATE TABLE DOCTORS(
    DOCTOR_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DOCTOR_NAME VARCHAR(255) NOT NULL,
    DEPARTMENT_ID INT UNSIGNED NOT NULL,
    SPECIALIZATION VARCHAR(100) NOT NULL,
    PHONE BIGINT NOT NULL,
    EXPERIENCE INT NOT NULL
)AUTO_INCREMENT=401;

      CREATE TABLE DEPARTMENTS(
        DEPARTMENT_ID INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
        DEPARTMENT_NAME VARCHAR(100) NOT NULL,
        FLOOR_NO INT UNSIGNED NOT NULL
      )AUTO_INCREMENT=301;
      
      CREATE TABLE APPOINTMENTS(
        APPOINTMENT_ID INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
        PATIENT_ID INT UNSIGNED NOT NULL,
        DOCTOR_ID INT UNSIGNED NOT NULL,
        APPOINTMENT_DATE DATE NOT NULL,
        APPOINTMENT_TIME TIME NOT NULL,
        STATUS VARCHAR(100) NOT NULL
      )AUTO_INCREMENT=101;

     CREATE TABLE Billing(
    Bill_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Patient_id INT UNSIGNED NOT NULL,
    Total_amount DECIMAL(10,2) NOT NULL,
    Bill_date DATE NOT NULL,
    Payment_status VARCHAR(100) NOT NULL
)AUTO_INCREMENT=1501;

CREATE TABLE Payments(
    Payment_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Bill_id INT UNSIGNED NOT NULL,
    Payment_date DATE NOT NULL,
    Payment_method VARCHAR(100) NOT NULL,
    Amount_paid DECIMAL(10,2) NOT NULL
)AUTO_INCREMENT=1601;

CREATE TABLE Prescriptions(
    Prescription_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Patient_id INT UNSIGNED NOT NULL,
    Prescription_date DATE NOT NULL,
    Notes VARCHAR(255) NOT NULL
)AUTO_INCREMENT=601;

CREATE TABLE Medicines(
    Medicine_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Medicine_name VARCHAR(255) NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    Stock_quantity INT NOT NULL
)AUTO_INCREMENT=701;

CREATE TABLE Prescription_medicines(
    Prescription_id INT UNSIGNED NOT NULL,
    Medicine_id INT UNSIGNED NOT NULL,
    Dosage VARCHAR(255) NOT NULL,
    Days INT NOT NULL,
    PRIMARY KEY (Prescription_id, Medicine_id)
);

CREATE TABLE Rooms(
    Room_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Room_type VARCHAR(255) NOT NULL,
    Room_charge DECIMAL(10,2) NOT NULL,
    Availability_status VARCHAR(100) NOT NULL
)AUTO_INCREMENT=1201;

CREATE TABLE Admissions(
    Admission_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Patient_id INT UNSIGNED NOT NULL,
    Room_id INT UNSIGNED NOT NULL,
    Admission_date DATE NOT NULL,
    Discharge_date DATE NOT NULL
)AUTO_INCREMENT=201;

CREATE TABLE Lab_tests(
    Test_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Patient_id INT UNSIGNED NOT NULL,
    Doctor_id INT UNSIGNED NOT NULL,
    Test_name VARCHAR(255) NOT NULL,
    Test_date DATE NOT NULL,
    Test_result VARCHAR(255) NOT NULL
)AUTO_INCREMENT=501;

CREATE TABLE Insurance(
    Insurance_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Patient_id INT UNSIGNED NOT NULL,
    Provider_name VARCHAR(255) NOT NULL,
    Policy_name VARCHAR(255) NOT NULL,
    Coverage_amount DECIMAL(10,2) NOT NULL
)AUTO_INCREMENT=1001;

CREATE TABLE Nurses(
    Nurse_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nurse_name VARCHAR(255) NOT NULL,
    Department_id INT UNSIGNED NOT NULL,
    Shift VARCHAR(100) NOT NULL
)AUTO_INCREMENT=801;

CREATE TABLE Staffs(
    Staff_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Staff_name VARCHAR(255) NOT NULL,
    Role VARCHAR(255) NOT NULL,
    Salary DECIMAL(10,2) NOT NULL,
    Department_id INT UNSIGNED NOT NULL
)AUTO_INCREMENT=901;

ALTER TABLE DOCTORS 
ADD constraint  DOCTORS_DEPARTMENT_ID_FK 
foreign key (DEPARTMENT_ID)  
references DEPARTMENTS(DEPARTMENT_ID);

ALTER TABLE APPOINTMENTS
ADD constraint APPOINTMENT_PATIENT_ID_FK
foreign key(patient_id)
references PATIENTS(PATIENT_ID);

ALTER TABLE APPOINTMENTS
ADD constraint APPOINTMENT_DOCTOR_ID_FK
FOREIGN KEY (DOCTOR_ID)
REFERENCES DOCTORS(DOCTOR_ID);

ALTER TABLE BILLING
ADD CONSTRAINT BILLING_PATIENT_ID_FK
FOREIGN KEY (PATIENT_ID)
REFERENCES PATIENTS(PATIENT_ID);

ALTER TABLE PAYMENTS
ADD CONSTRAINT PAYMENT_BILL_ID_FK
FOREIGN KEY (BILL_ID)
REFERENCES BILLING(BILL_ID);

ALTER TABLE PRESCRIPTIONS
ADD CONSTRAINT PRESCRIPTIONS_PATIENT_ID_FK
FOREIGN KEY (PATIENT_ID)
REFERENCES PATIENTS(PATIENT_ID);

ALTER TABLE Prescription_medicines
ADD CONSTRAINT PRESCRIPTION_MEDICINES_PRESCRIPTION_ID
FOREIGN KEY (Prescription_ID)
REFERENCES PrescriptionS(Prescription_ID);

ALTER TABLE PRESCRIPTION_MEDICINES
ADD CONSTRAINT PRESCRIPTION_MEDICINES_MEDICINE_ID
FOREIGN KEY (MEDICINE_ID)
REFERENCES MEDICINES(MEDICINE_ID);

ALTER TABLE ADMISSIONS
ADD CONSTRAINT ADMISSIONS_PATIENT_ID_FK
FOREIGN KEY (PATIENT_ID)
REFERENCES PATIENTS(PATIENT_ID);

ALTER TABLE ADMISSIONS
ADD CONSTRAINT ADMISSIONS_ROOM_ID_FK
FOREIGN KEY (ROOM_ID)
REFERENCES ROOMS(ROOM_ID);

ALTER TABLE LAB_TESTS
ADD CONSTRAINT LAB_TESTS_PATIENT_ID_FK
FOREIGN KEY(PATIENT_ID)
REFERENCES PATIENTS(PATIENT_ID);

ALTER TABLE LAB_TESTS
ADD CONSTRAINT LAB_TESTS_DOCTOR_ID_FK
FOREIGN KEY(DOCTOR_ID)
REFERENCES DOCTORS(DOCTOR_ID);

ALTER TABLE Insurance
ADD CONSTRAINT Insurance_PATIENT_ID_FK
FOREIGN KEY(PATIENT_ID)
REFERENCES PATIENTS(PATIENT_ID);

ALTER TABLE NURSES
ADD CONSTRAINT NURSES_DEPARTMENT_ID_FK
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPARTMENTS(DEPARTMENT_ID);

ALTER TABLE STAFFS
ADD CONSTRAINT STAFFS_DEPARTMENT_ID_FK
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPARTMENTS(DEPARTMENT_ID);


